c_compiler:     # [win]
- vs2017        # [win]
- vs2017        # [win]
- vs2017        # [win]
cxx_compiler:   # [win]
- vs2017        # [win]
- vs2017        # [win]
- vs2017        # [win]
python:         # [win]
- '3.6'         # [win]
- '3.7'         # [win]
- '3.8'         # [win]
vc:             # [win]
- '14.1'        # [win]
- '14.1'        # [win]
- '14.1'        # [win]
channel_sources:
  - ramonaoptics,conda-forge,defaults
channel_targets:
  - ramonaoptics main
